import React, { useState } from 'react';
import {
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  Info,
  Copy,
  Check,
  Download,
  Share2,
  TrendingUp,
  ShieldAlert,
  HelpCircle,
  Sparkles,
  Calendar,
  Layers,
  Award,
  DollarSign,
  ChevronRight,
  FileCheck,
} from 'lucide-react';
import { StrategyResult } from '../types.js';

interface ExecutiveDashboardProps {
  result: StrategyResult;
  onModifyInputs: () => void;
  onNewAnalysis: () => void;
}

export const ExecutiveDashboard: React.FC<ExecutiveDashboardProps> = ({
  result,
  onModifyInputs,
  onNewAnalysis,
}) => {
  const [copied, setCopied] = useState(false);
  const [showMetadataTooltip, setShowMetadataTooltip] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'frameworks' | 'action-plan'>('overview');

  const { query, category, marketSizing, frameworks, recommendation } = result;

  const handleCopyReport = () => {
    const reportText = `STRATEGIC DIRECTION BRIEF: ${query.companyType} in ${query.sector}
Location: ${query.location}
Problem Statement: "${query.problemStatement}"

CATEGORY: ${category}
OVERALL ATTRACTIVENESS SCORE: ${recommendation.attractivenessScore}/100 (${recommendation.attractivenessLabel})

CORE DIRECTIONAL VERDICT:
${recommendation.verdictHeadline}

EXECUTIVE SUMMARY:
${recommendation.verdictSummary}

MARKET SIZING (2026 Sector DB):
- TAM: ${marketSizing.tam.value} (${marketSizing.tam.detail})
- SAM: ${marketSizing.sam.value} (${marketSizing.sam.detail})
- SOM: ${marketSizing.som.value} (${marketSizing.som.detail})
- Willingness to Pay (WTP): ${marketSizing.wtp.pricePremiumDelta} premium headroom
- Key Value Driver: ${marketSizing.wtp.keyDriver}

SELECTED STRATEGIC FRAMEWORKS:
${frameworks.map((f, i) => `${i + 1}. ${f.name} (${f.originatorOrLens})\n   - Why Picked: ${f.whyPicked}\n   - Key Takeaway: ${f.plainEnglishTakeaway}`).join('\n\n')}

EXECUTIVE 3-STEP ACTION PLAN:
Step 1: ${recommendation.threeStepPlan.step1WhatToDoFirst.actionTitle}
${recommendation.threeStepPlan.step1WhatToDoFirst.concreteMoves.map((m) => `   * ${m}`).join('\n')}

Step 2 (What NOT to do): ${recommendation.threeStepPlan.step2WhatNotToDo.nonGoalTitle}
${recommendation.threeStepPlan.step2WhatNotToDo.forbiddenTraps.map((t) => `   * [NON-GOAL] ${t}`).join('\n')}

Step 3 (Execution Risks & Countermeasures):
${recommendation.threeStepPlan.step3ExecutionRisks.risks.map((r) => `   * ${r.risk} (${r.impactLevel} Impact): ${r.plainEnglishWarning} -> Countermeasure: ${r.countermeasure}`).join('\n')}

HORIZON MILESTONES:
- Next 30 Days: ${recommendation.horizonMilestones.days30}
- Next 60 Days: ${recommendation.horizonMilestones.days60}
- Next 90 Days: ${recommendation.horizonMilestones.days90}
`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleDownloadMarkdown = () => {
    const filename = `Strategic_Direction_${query.sector.replace(/[^a-z0-9]/gi, '_')}.md`;
    const reportText = `# Strategic Direction Agent — Executive Brief
**Company:** ${query.companyType} | **Sector:** ${query.sector} | **Geography:** ${query.location}
**Problem Statement:** "${query.problemStatement}"

---

## Strategic Verdict
**Score:** ${recommendation.attractivenessScore}/100 — ${recommendation.attractivenessLabel}
**Core Directional Verdict:** ${recommendation.verdictHeadline}

> ${recommendation.verdictSummary}

---

## Market Sizing & Willingness to Pay (WTP)
- **TAM (Total Addressable Market):** ${marketSizing.tam.value} (${marketSizing.tam.detail})
- **SAM (Serviceable Addressable Market):** ${marketSizing.sam.value} (${marketSizing.sam.detail})
- **SOM (Serviceable Obtainable Market):** ${marketSizing.som.value} (${marketSizing.som.detail})
- **WTP Premium Potential:** ${marketSizing.wtp.pricePremiumDelta}
- **Value Driver:** ${marketSizing.wtp.keyDriver}

---

## Dynamic Framework Lens Analysis
${frameworks.map((f) => `### ${f.name}
- **Lens:** ${f.originatorOrLens}
- **Why Picked:** ${f.whyPicked}
- **Plain-English Takeaway:** ${f.plainEnglishTakeaway}
`).join('\n')}

---

## 3-Step Plain-English Action Plan

### 1. What To Do First
**${recommendation.threeStepPlan.step1WhatToDoFirst.actionTitle}**
${recommendation.threeStepPlan.step1WhatToDoFirst.concreteMoves.map((m) => `- ${m}`).join('\n')}

### 2. What NOT To Do (Trade-Offs & Non-Goals)
**${recommendation.threeStepPlan.step2WhatNotToDo.nonGoalTitle}**
${recommendation.threeStepPlan.step2WhatNotToDo.forbiddenTraps.map((t) => `- ${t}`).join('\n')}

### 3. Key Execution Risks & Mitigations
${recommendation.threeStepPlan.step3ExecutionRisks.risks.map((r) => `- **${r.risk}** (${r.impactLevel} Impact): ${r.plainEnglishWarning}
  *Mitigation:* ${r.countermeasure}`).join('\n')}

---
*Generated by Strategic Direction Agent | Source: Sector DB 2026 | Location: ${marketSizing.metadata.targetGeo} | Confidence: ${marketSizing.metadata.confidence}*
`;

    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="w-full max-w-6xl mx-auto py-8 px-4 sm:px-6 space-y-8">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-200">
        <div className="flex items-center gap-2">
          <button
            id="back-to-input-btn"
            onClick={onModifyInputs}
            className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-700 bg-white hover:bg-slate-50 active:bg-slate-100 border border-slate-200 px-3 py-1.5 rounded-lg transition-colors cursor-pointer"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Modify Context</span>
          </button>
          <span className="text-xs text-slate-500 font-mono hidden md:inline">
            Screen 3: Executive Dashboard
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            id="copy-report-btn"
            onClick={handleCopyReport}
            className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-800 bg-white hover:bg-slate-50 active:bg-slate-100 border border-slate-200 px-3 py-1.5 rounded-lg transition-colors cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Brief' : 'Copy Brief'}</span>
          </button>

          <button
            id="download-report-btn"
            onClick={handleDownloadMarkdown}
            className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-800 bg-white hover:bg-slate-50 active:bg-slate-100 border border-slate-200 px-3 py-1.5 rounded-lg transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Markdown</span>
          </button>

          <button
            id="new-analysis-btn"
            onClick={onNewAnalysis}
            className="inline-flex items-center gap-1.5 text-xs font-medium text-white bg-slate-900 hover:bg-slate-800 active:bg-slate-950 px-3.5 py-1.5 rounded-lg transition-colors cursor-pointer shadow-xs"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>New Query</span>
          </button>
        </div>
      </div>

      {/* TOP SUMMARY BANNER: Overall Attractiveness Score & Core Directional Verdict */}
      <section
        id="top-summary-banner"
        className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-8 shadow-xs relative overflow-hidden"
      >
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
          <div className="flex-1 min-w-0">
            {/* Category tag */}
            <div className="flex flex-wrap items-center gap-2 mb-3">
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-slate-900 text-white">
                {category}
              </span>
              <span className="text-xs text-slate-500">
                {query.companyType} • {query.sector} • {query.location}
              </span>
            </div>

            {/* Core Directional Verdict */}
            <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold tracking-tight text-slate-950 mb-3 leading-snug">
              {recommendation.verdictHeadline}
            </h2>

            {/* Verdict Plain English Summary */}
            <p className="text-sm sm:text-base text-slate-700 leading-relaxed max-w-3xl">
              {recommendation.verdictSummary}
            </p>
          </div>

          {/* Attractiveness Score Badge & Metric */}
          <div className="shrink-0 w-full lg:w-auto bg-slate-50 border border-slate-200 rounded-xl p-5 flex flex-row lg:flex-col items-center justify-between lg:justify-center text-center gap-3">
            <div>
              <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                Attractiveness Score
              </div>
              <div className="flex items-baseline justify-center gap-1">
                <span className="text-4xl sm:text-5xl font-extrabold tracking-tight text-slate-900">
                  {recommendation.attractivenessScore}
                </span>
                <span className="text-sm font-semibold text-slate-500">/100</span>
              </div>
            </div>
            <div className="text-right lg:text-center">
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-semibold bg-emerald-100 text-emerald-800 border border-emerald-200">
                <Award className="w-3.5 h-3.5" />
                {recommendation.attractivenessLabel}
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* MARKET SIZING METRICS GRID */}
      <section id="market-sizing-section" className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h3 className="text-lg font-bold tracking-tight text-slate-900 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-slate-700" />
              <span>Market Sizing & Value Assessment</span>
            </h3>
            <p className="text-xs text-slate-500">
              TAM, SAM, SOM calibrated to {marketSizing.metadata.targetGeo} with Willingness to Pay (WTP) delta.
            </p>
          </div>

          {/* Metadata Tooltip: [Source: Sector DB 2026 | Location: Specified Geo | Confidence: Medium-High] */}
          <div className="relative">
            <button
              id="metadata-tooltip-trigger"
              onClick={() => setShowMetadataTooltip(!showMetadataTooltip)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 border border-slate-200 transition-colors cursor-pointer"
            >
              <Info className="w-3.5 h-3.5 text-slate-500" />
              <span>
                [Source: {marketSizing.metadata.source} | Location: {marketSizing.metadata.targetGeo} | Confidence: {marketSizing.metadata.confidence}]
              </span>
            </button>

            {showMetadataTooltip && (
              <div className="absolute right-0 mt-2 w-80 sm:w-96 bg-white border border-slate-200 rounded-xl p-4 shadow-lg text-xs text-slate-600 z-20 space-y-2">
                <div className="font-semibold text-slate-900 flex items-center justify-between">
                  <span>Market Sizing Methodology</span>
                  <span className="text-slate-400 font-mono text-2xs">Base Year: {marketSizing.metadata.baseYear}</span>
                </div>
                <p>
                  Estimates combine 2026 macroeconomic consumption indicators with localized urban concentration multipliers for{' '}
                  <span className="font-semibold text-slate-800">{marketSizing.metadata.targetGeo}</span>.
                </p>
                <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-slate-500 text-2xs">
                  <span>Forecast Horizon: {marketSizing.metadata.horizon}</span>
                  <button
                    onClick={() => setShowMetadataTooltip(false)}
                    className="text-slate-700 font-medium hover:underline"
                  >
                    Close
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* 4-Card Metrics Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* TAM Card */}
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between text-xs font-semibold text-slate-500 mb-1">
                <span>TAM (Total Market)</span>
                {marketSizing.tam.cagr && (
                  <span className="text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded text-2xs font-semibold">
                    {marketSizing.tam.cagr}
                  </span>
                )}
              </div>
              <div className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-1.5">
                {marketSizing.tam.value}
              </div>
              <div className="text-xs font-medium text-slate-700 mb-2">{marketSizing.tam.detail}</div>
            </div>
            <p className="text-xs text-slate-500 pt-2 border-t border-slate-100">
              {marketSizing.tam.description}
            </p>
          </div>

          {/* SAM Card */}
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between text-xs font-semibold text-slate-500 mb-1">
                <span>SAM (Serviceable Market)</span>
                <span className="text-indigo-700 bg-indigo-50 px-1.5 py-0.5 rounded text-2xs font-semibold">
                  Target Segment
                </span>
              </div>
              <div className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-1.5">
                {marketSizing.sam.value}
              </div>
              <div className="text-xs font-medium text-slate-700 mb-2">{marketSizing.sam.detail}</div>
            </div>
            <p className="text-xs text-slate-500 pt-2 border-t border-slate-100">
              {marketSizing.sam.description}
            </p>
          </div>

          {/* SOM Card */}
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between text-xs font-semibold text-slate-500 mb-1">
                <span>SOM (12-18M Target)</span>
                <span className="text-amber-800 bg-amber-50 px-1.5 py-0.5 rounded text-2xs font-semibold">
                  Obtainable
                </span>
              </div>
              <div className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-1.5">
                {marketSizing.som.value}
              </div>
              <div className="text-xs font-medium text-slate-700 mb-2">{marketSizing.som.detail}</div>
            </div>
            <p className="text-xs text-slate-500 pt-2 border-t border-slate-100">
              {marketSizing.som.description}
            </p>
          </div>

          {/* Willingness to Pay (WTP) Assessment Card */}
          <div className="bg-slate-900 text-white rounded-xl p-5 shadow-xs flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between text-xs font-semibold text-slate-300 mb-1">
                <span>Delta WTP Assessment</span>
                <span className="text-emerald-400 bg-emerald-950 px-2 py-0.5 rounded text-2xs font-semibold border border-emerald-800">
                  {marketSizing.wtp.scoreRating}
                </span>
              </div>
              <div className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight mb-1.5">
                {marketSizing.wtp.pricePremiumDelta}
              </div>
              <div className="text-xs text-slate-200 line-clamp-2 mb-2 font-medium">
                {marketSizing.wtp.keyDriver}
              </div>
            </div>
            <p className="text-xs text-slate-300 pt-2 border-t border-slate-800">
              {marketSizing.wtp.elasticitySummary}
            </p>
          </div>
        </div>
      </section>

      {/* SELECTED FRAMEWORKS SECTION: 4-5 Cards showing WHICH and WHY */}
      <section id="selected-frameworks-section" className="space-y-4">
        <div>
          <h3 className="text-lg font-bold tracking-tight text-slate-900 flex items-center gap-2">
            <Layers className="w-5 h-5 text-slate-700" />
            <span>Selected Strategy Frameworks ({frameworks.length} Lenses Applied)</span>
          </h3>
          <p className="text-xs text-slate-500">
            Dynamically matched from the 15-framework library to analyze this exact problem without forcing academic jargon.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {frameworks.map((fw, idx) => (
            <div
              key={fw.id}
              id={`framework-card-${fw.id}`}
              className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs flex flex-col justify-between hover:border-slate-400 transition-all"
            >
              <div>
                {/* Header with lens number and category badge */}
                <div className="flex items-center justify-between gap-2 mb-2.5">
                  <span className="text-xs font-mono font-bold text-slate-400">
                    LENS 0{idx + 1}
                  </span>
                  <span className="text-2xs font-semibold px-2 py-0.5 rounded-md bg-slate-100 text-slate-700 border border-slate-200">
                    {fw.strategicCategory}
                  </span>
                </div>

                <h4 className="text-base font-bold text-slate-900 mb-1">
                  {fw.name}
                </h4>
                <div className="text-2xs text-slate-500 font-medium mb-3">
                  {fw.originatorOrLens}
                </div>

                {/* Why Picked for this problem */}
                <div className="mb-3.5 bg-slate-50/80 border border-slate-200/80 rounded-lg p-3">
                  <div className="text-2xs font-bold text-slate-900 uppercase tracking-wider mb-1">
                    Why Picked For Your Problem:
                  </div>
                  <p className="text-xs text-slate-700 leading-relaxed">
                    {fw.whyPicked}
                  </p>
                </div>

                {/* Plain-English Takeaway */}
                <div className="mb-3">
                  <div className="text-2xs font-bold text-slate-900 uppercase tracking-wider mb-1">
                    Plain-English Actionable Takeaway:
                  </div>
                  <p className="text-xs text-slate-900 font-medium leading-relaxed">
                    "{fw.plainEnglishTakeaway}"
                  </p>
                </div>
              </div>

              {/* Application questions */}
              {fw.applicationQuestions && fw.applicationQuestions.length > 0 && (
                <div className="pt-3 border-t border-slate-100">
                  <div className="text-2xs font-semibold text-slate-500 mb-1.5">Leadership Team Questions:</div>
                  <ul className="text-2xs text-slate-600 space-y-1">
                    {fw.applicationQuestions.map((q, qIdx) => (
                      <li key={qIdx} className="flex items-start gap-1.5">
                        <ChevronRight className="w-3 h-3 text-slate-400 shrink-0 mt-0.5" />
                        <span>{q}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* EXECUTIVE RECOMMENDATION: Clear 3-Step Action Plan */}
      <section id="executive-recommendation-section" className="space-y-4">
        <div>
          <h3 className="text-lg font-bold tracking-tight text-slate-900 flex items-center gap-2">
            <FileCheck className="w-5 h-5 text-slate-700" />
            <span>Executive Recommendation: 3-Step Action Plan</span>
          </h3>
          <p className="text-xs text-slate-500">
            Plain-English directional execution: what to prioritize, what to explicitly avoid, and key risks to mitigate.
          </p>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-8 shadow-xs space-y-8">
          {/* STEP 1: What to do first */}
          <div id="action-plan-step-1" className="space-y-3">
            <div className="flex items-center gap-2.5">
              <span className="w-7 h-7 rounded-lg bg-emerald-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                1
              </span>
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-emerald-700">
                  STEP 1: What To Do First (Core Strategy)
                </span>
                <h4 className="text-base sm:text-lg font-bold text-slate-900">
                  {recommendation.threeStepPlan.step1WhatToDoFirst.actionTitle}
                </h4>
              </div>
            </div>

            <p className="text-xs sm:text-sm text-slate-600 pl-9.5">
              {recommendation.threeStepPlan.step1WhatToDoFirst.rationale}
            </p>

            <div className="pl-9.5 grid grid-cols-1 gap-2 pt-1">
              {recommendation.threeStepPlan.step1WhatToDoFirst.concreteMoves.map((move, mIdx) => (
                <div
                  key={mIdx}
                  className="flex items-start gap-2.5 bg-emerald-50/50 border border-emerald-100 rounded-lg p-3 text-xs text-emerald-950 font-medium"
                >
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                  <span>{move}</span>
                </div>
              ))}
            </div>
          </div>

          <hr className="border-slate-100" />

          {/* STEP 2: What NOT to do */}
          <div id="action-plan-step-2" className="space-y-3">
            <div className="flex items-center gap-2.5">
              <span className="w-7 h-7 rounded-lg bg-rose-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                2
              </span>
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-rose-700">
                  STEP 2: What NOT To Do (Trade-Offs & Non-Goals)
                </span>
                <h4 className="text-base sm:text-lg font-bold text-slate-900">
                  {recommendation.threeStepPlan.step2WhatNotToDo.nonGoalTitle}
                </h4>
              </div>
            </div>

            <p className="text-xs sm:text-sm text-slate-600 pl-9.5">
              {recommendation.threeStepPlan.step2WhatNotToDo.rationale}
            </p>

            <div className="pl-9.5 grid grid-cols-1 gap-2 pt-1">
              {recommendation.threeStepPlan.step2WhatNotToDo.forbiddenTraps.map((trap, tIdx) => (
                <div
                  key={tIdx}
                  className="flex items-start gap-2.5 bg-rose-50/40 border border-rose-100 rounded-lg p-3 text-xs text-rose-950 font-medium"
                >
                  <ShieldAlert className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
                  <span>
                    <strong className="text-rose-800">[NON-GOAL]</strong> {trap}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <hr className="border-slate-100" />

          {/* STEP 3: Execution Risks */}
          <div id="action-plan-step-3" className="space-y-3">
            <div className="flex items-center gap-2.5">
              <span className="w-7 h-7 rounded-lg bg-amber-600 text-white font-bold text-xs flex items-center justify-center shrink-0">
                3
              </span>
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-amber-700">
                  STEP 3: Key Execution Risks & Mitigations
                </span>
                <h4 className="text-base sm:text-lg font-bold text-slate-900">
                  External Vulnerabilities & Operational Neutralizers
                </h4>
              </div>
            </div>

            <p className="text-xs sm:text-sm text-slate-600 pl-9.5">
              {recommendation.threeStepPlan.step3ExecutionRisks.summary}
            </p>

            <div className="pl-9.5 grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
              {recommendation.threeStepPlan.step3ExecutionRisks.risks.map((risk, rIdx) => (
                <div
                  key={rIdx}
                  className="bg-amber-50/40 border border-amber-200/70 rounded-xl p-4 space-y-2 text-xs"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-amber-950">{risk.risk}</span>
                    <span
                      className={`text-2xs font-semibold px-2 py-0.5 rounded ${
                        risk.impactLevel === 'High'
                          ? 'bg-rose-100 text-rose-800'
                          : 'bg-amber-100 text-amber-800'
                      }`}
                    >
                      {risk.impactLevel} Impact
                    </span>
                  </div>
                  <p className="text-slate-700 leading-relaxed">{risk.plainEnglishWarning}</p>
                  <div className="pt-2 border-t border-amber-200/50 text-slate-900">
                    <span className="font-semibold text-amber-900">Countermeasure: </span>
                    <span>{risk.countermeasure}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <hr className="border-slate-100" />

          {/* 30-60-90 Day Execution Milestones */}
          <div className="pt-2">
            <div className="flex items-center gap-2 mb-3">
              <Calendar className="w-4 h-4 text-slate-700" />
              <h5 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                Execution Horizon Milestones (Next 90 Days)
              </h5>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-3.5 text-xs">
                <span className="font-bold text-slate-900 block mb-1">Days 1–30</span>
                <p className="text-slate-600 leading-relaxed">{recommendation.horizonMilestones.days30}</p>
              </div>
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-3.5 text-xs">
                <span className="font-bold text-slate-900 block mb-1">Days 31–60</span>
                <p className="text-slate-600 leading-relaxed">{recommendation.horizonMilestones.days60}</p>
              </div>
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-3.5 text-xs">
                <span className="font-bold text-slate-900 block mb-1">Days 61–90</span>
                <p className="text-slate-600 leading-relaxed">{recommendation.horizonMilestones.days90}</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer / Reset Prompt */}
      <div className="text-center pt-4 pb-12">
        <button
          onClick={onNewAnalysis}
          className="inline-flex items-center gap-2 bg-slate-900 hover:bg-slate-800 active:bg-slate-950 text-white font-medium text-sm px-6 py-3 rounded-xl shadow-xs transition-colors cursor-pointer"
        >
          <Sparkles className="w-4 h-4" />
          <span>Analyze Another Business Scenario</span>
        </button>
      </div>
    </div>
  );
};
